#!/bin/sh
if [ "${1-}" = configure ] && [ -n "${CONFIGURE_LOG:-}" ]; then
  printf 'configure invoked\n' >> "$CONFIGURE_LOG"
  printf '\033[?1049hconfigure-ui-stdout\033[?1049l\n'
  printf 'configure-ui-stderr\n' >&2
fi
exit "${CONFIGURE_STATUS:-0}"
